// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActionsStart(arg1, arg2, arg3, arg4) {
  return window['go']['apps']['App']['ActionsStart'](arg1, arg2, arg3, arg4);
}

export function ConfigJavaAddOrUpdate(arg1) {
  return window['go']['apps']['App']['ConfigJavaAddOrUpdate'](arg1);
}

export function ConfigJavaDelete(arg1) {
  return window['go']['apps']['App']['ConfigJavaDelete'](arg1);
}

export function ConfigJavaGetList() {
  return window['go']['apps']['App']['ConfigJavaGetList']();
}

export function ConfigPassAddOrUpdate(arg1) {
  return window['go']['apps']['App']['ConfigPassAddOrUpdate'](arg1);
}

export function ConfigPassDelete(arg1) {
  return window['go']['apps']['App']['ConfigPassDelete'](arg1);
}

export function ConfigPassGetList() {
  return window['go']['apps']['App']['ConfigPassGetList']();
}

export function ConfigPassSwitch(arg1, arg2) {
  return window['go']['apps']['App']['ConfigPassSwitch'](arg1, arg2);
}

export function DomReady(arg1) {
  return window['go']['apps']['App']['DomReady'](arg1);
}

export function Greet(arg1) {
  return window['go']['apps']['App']['Greet'](arg1);
}

export function SurveyStart(arg1) {
  return window['go']['apps']['App']['SurveyStart'](arg1);
}
