// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function CommonAction(arg1:model.ActionRequest):Promise<void>;

export function CommonSurvey(arg1:Array<string>):Promise<any>;

export function DomReady(arg1:context.Context):Promise<void>;

export function Greet(arg1:string):Promise<string>;
