// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigPassAddOrUpdate(arg1, arg2, arg3, arg4) {
  return window['go']['apps']['App']['ConfigPassAddOrUpdate'](arg1, arg2, arg3, arg4);
}

export function ConfigPassDelete(arg1) {
  return window['go']['apps']['App']['ConfigPassDelete'](arg1);
}

export function ConfigPassGetList() {
  return window['go']['apps']['App']['ConfigPassGetList']();
}

export function DomReady(arg1) {
  return window['go']['apps']['App']['DomReady'](arg1);
}

export function Greet(arg1) {
  return window['go']['apps']['App']['Greet'](arg1);
}
