// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function ConfigPassAddOrUpdate(arg1:number,arg2:string,arg3:string,arg4:string):Promise<model.WailsCommunicate>;

export function ConfigPassDelete(arg1:number):Promise<model.WailsCommunicate>;

export function ConfigPassGetList():Promise<model.WailsCommunicate>;

export function DomReady(arg1:context.Context):Promise<void>;

export function Greet(arg1:number):Promise<number>;
